################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
BufferAllocation_2.obj: ../BufferAllocation_2.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BufferAllocation_2.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS_ARP.obj: ../FreeRTOS_ARP.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS_ARP.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS_DHCP.obj: ../FreeRTOS_DHCP.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS_DHCP.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS_DNS.obj: ../FreeRTOS_DNS.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS_DNS.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS_IP.obj: ../FreeRTOS_IP.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS_IP.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS_Sockets.obj: ../FreeRTOS_Sockets.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS_Sockets.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS_Stream_Buffer.obj: ../FreeRTOS_Stream_Buffer.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS_Stream_Buffer.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS_TCP_IP.obj: ../FreeRTOS_TCP_IP.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS_TCP_IP.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS_TCP_WIN.obj: ../FreeRTOS_TCP_WIN.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS_TCP_WIN.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS_UDP_IP.obj: ../FreeRTOS_UDP_IP.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS_UDP_IP.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

adc.obj: ../adc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="adc.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

aes.obj: ../aes.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="aes.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

buttons.obj: ../buttons.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="buttons.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

can.obj: ../can.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="can.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

comp.obj: ../comp.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="comp.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

cpu.obj: ../cpu.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="cpu.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

crc.obj: ../crc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="crc.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

des.obj: ../des.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="des.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

eeprom.obj: ../eeprom.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="eeprom.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

emac.obj: ../emac.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="emac.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

epi.obj: ../epi.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="epi.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

epi_workaround_ccs.obj: ../epi_workaround_ccs.s $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="epi_workaround_ccs.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

exosite_hal_lwip.obj: ../exosite_hal_lwip.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="exosite_hal_lwip.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

flash.obj: ../flash.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="flash.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

fpu.obj: ../fpu.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="fpu.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

gpio.obj: ../gpio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="gpio.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

hibernate.obj: ../hibernate.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="hibernate.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

http.obj: ../http.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="http.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

i2c.obj: ../i2c.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="i2c.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

interrupt.obj: ../interrupt.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="interrupt.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

lcd.obj: ../lcd.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="lcd.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

mpu.obj: ../mpu.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="mpu.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

networkinterface.obj: /Users/gautham/Documents/APES_project1/networkinterface.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="networkinterface.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

onewire.obj: ../onewire.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="onewire.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

pinout.obj: ../pinout.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="pinout.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

pwm.obj: ../pwm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="pwm.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

qei.obj: ../qei.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="qei.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

shamd5.obj: ../shamd5.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="shamd5.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

ssi.obj: ../ssi.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="ssi.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

sw_crc.obj: ../sw_crc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="sw_crc.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

sysctl.obj: ../sysctl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="sysctl.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

sysexc.obj: ../sysexc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="sysexc.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

systick.obj: ../systick.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="systick.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

timer.obj: ../timer.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="timer.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

tm4c1294ncpdt_startup_ccs.obj: ../tm4c1294ncpdt_startup_ccs.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="tm4c1294ncpdt_startup_ccs.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

uart.obj: ../uart.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="uart.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

udma.obj: ../udma.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="udma.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

usb.obj: ../usb.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="usb.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

watchdog.obj: ../watchdog.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="watchdog.d_raw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


