################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
FreeRTOS/Source/croutine.obj: ../FreeRTOS/Source/croutine.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS/Source/croutine.d_raw" --obj_directory="FreeRTOS/Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS/Source/event_groups.obj: ../FreeRTOS/Source/event_groups.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS/Source/event_groups.d_raw" --obj_directory="FreeRTOS/Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS/Source/list.obj: ../FreeRTOS/Source/list.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS/Source/list.d_raw" --obj_directory="FreeRTOS/Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS/Source/queue.obj: ../FreeRTOS/Source/queue.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS/Source/queue.d_raw" --obj_directory="FreeRTOS/Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS/Source/stream_buffer.obj: ../FreeRTOS/Source/stream_buffer.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS/Source/stream_buffer.d_raw" --obj_directory="FreeRTOS/Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS/Source/tasks.obj: ../FreeRTOS/Source/tasks.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS/Source/tasks.d_raw" --obj_directory="FreeRTOS/Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS/Source/timers.obj: ../FreeRTOS/Source/timers.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me --include_path="/Users/gautham/workspace_v8/proj_2" --include_path="/Users/gautham/Documents/APES_project1/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/third_party/exosite/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/examples/boards/ek-tm4c1294xl/drivers/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/inc/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/include/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/portable/CCS/ARM_CM4F/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/driverlib" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/utils/" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS/Source/include/" --include_path="/Users/gautham/workspace_v8/proj_2/FreeRTOS" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP" --include_path="/Applications/ti/ccsv8/FreeRTOSv10.0.1/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/Compiler/GCC/" --include_path="/Applications/ti/ccsv8/SW-TM4C-2.1.4.178/" --include_path="/Applications/ti/ccsv8/tools/compiler/ti-cgt-arm_18.1.1.LTS/include" --define=ccs="ccs" --define=PART_TM4C1294NCPDT -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="FreeRTOS/Source/timers.d_raw" --obj_directory="FreeRTOS/Source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


